framework: jest
preRun:
  command:
    - yarn install
postMerge:
  pattern:
    - "./test/*.unittest.js"
preMerge:
  pattern:
    - "./test/*.unittest.js"
postRun:
  command:
    - yarn --version
version: 1.0
