framework: jest
preRun:
  command:
    - yarn install
postMerge:
  pattern:
    - "./test/WasmHashes.unittest.js"
preMerge:
  pattern:
    - "./test/WasmHashes.unittest.js"
postRun:
  command:
    - yarn --version
version: 1.0
